//------------------------------------------------------------------------
// Copyright(c) 2025 Laser Brain.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"K-wire 2.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"K-wire 2 VST3 (64Bit)"
#else
#define stringFileDescription	"K-wire 2 VST3"
#endif
#define stringCompanyName		"Laser Brain\0"
#define stringLegalCopyright	"Copyright(c) 2025 Laser Brain."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
